os: Visual Studio 2015

# Build script
build_script:
  - ps: .\build.ps1

# Tests
test: off

# Build cache
cache:
  - packages -> **\packages.config

artifacts:
  - path: artifacts\nuget-package\*.nupkg
